### ISSUE TITLE
Paper scripts give error

### ISSUE THREAD

**Issue by bcossins** [essex-lab/grand#1]
Hi,
Many thanks for making your great GCMC code available.
I have installed with the following:
```
bash ./Miniconda-py37_4.9.2-Linux-x86_64.sh -b -p /opt/MD-software/miniconda3-grand
conda install --yes -c omnia -c anaconda -c conda-forge -c essexlab grand
conda install --yes -c omnia/label/cuda92 -c conda-forge openmm
```

Then downloaded and tried the paper BPTI scripts from [bpti gcmc-md](https://github.com/essex-lab/grand-paper/tree/master/bpti/gcmc-md).
When I do:
```
cd gcmc-md/equil/
python equil-uvt1.py
```
The simulation runs fine and carried out 110k std GCMC moves but it dies before it can write out the final pdb - bpti-uvt1.pdb. Has the latest code changes in relation to this command?
```
pdb.topology, pdb.positions = grand.utils.remove_ghosts(pdb.topology, positions,
                                                        ghosts=ghost_resids,
                                                        pdb='bpti-uvt1.pdb')
```

**Comment by olliemelling** [comment]
Hi,

Thanks for raising this. The issue here is that the paper scripts were written to run with version 1.0.x of grand and due to some changes we made in version 1.1.0 with regards to storing the status of water molecules, line 76 of equil-uvt1.py now returns an error with v1.1.0.

I will add a note to the README of the grand repo where it links to the paper examples to indicate that these are intended to be run with v1.0.x and I'll also update the equilibration scripts so that they work with v1.1.0 and will add them to the main repo (will leave the paper scripts as they are just so they match with the release of the code at the time of the paper's publication).

In the meantime, if you wish to run these examples in v1.0.1 then the conda command just needs to be replaced with:
`conda install --yes -c omnia -c anaconda -c conda-forge -c essexlab grand=1.0.1
`

Ollie

**Comment by olliemelling** [comment]
The BPTI examples within the _grand_ repo (can be found [here](https://github.com/essex-lab/grand/tree/master/examples/bpti)) are now more comprehensive, in line with the paper examples from the 2020 publication and are adapted to run with v1.1.0.

If you wish to run any of the other paper scripts, such as the water density calculations or calculation of the GCMC parameters then I would recommend doing this with version 1.0.1.

If you can confirm these now work for you then I will close this issue.

Ollie

**Comment by bcossins** [comment]
Thanks Ollie, will have a go tonight and let you know.

**Comment by bcossins** [comment]
This works for me too. Thanks again.
