### ISSUE TITLE
Particle coordinate is NaN when using GCNCMC with OpenMM 8.0.0

### ISSUE THREAD

**Issue by LilDojd** [essex-lab/grand#10]
Hi! 

I was running pytests with OpenMM 8.0.0 with a few tweaks (chaged simtk imports to openmm). Tests for NonequilibriumGCMC samplers fail with `openmm.OpenMMException: Particle coordinate is NaN`. The earliest OpenMM version I was able to get it working with was OpenMM 7.7.0

I've looked into code and OpenMM changelogs and could not figure out the reason behind such behavior. Even a single step of NonequilibriumLangevinIntegrator leads to explosions at both insertion and deletion moves. 

Are you planning to provide support for newer OpenMM versions? Folks at @cresset-group have a fork with various enhancements and OpenMM 8.0.0 compatibility, but I was not able to get it working either.

**Comment by olliemelling** [comment]
Hi,

Thanks for raising this - the tests were written using the built-in OpenMM LangevinIntegrator which did work in older versions of OpenMM but appears to be no longer stable for use in grand.

Either the BAOABIntegrator or NonequilibriumLangevinIntegrator from openmmtools should run fine with grand and OpenMM v8.0.0, this can be tested by running the examples that come with grand.

It appears that the reason some of the tests are also failing when you try the NonequilibriumLangevinIntegrator instead is due to there being too few perturbation and propagation steps in the GCNCMC move, rather than an issue with the actual integrator itself.

If you run the examples with either of the two openmmtools integrators above then they should run fine. I will update the tests later today to fix this.

Thanks,

Ollie

**Comment by LilDojd** [comment]
Tests passed with flying colors. Thank you so much! Closing issue
