### ISSUE TITLE
Protein-ligand GCMC simulations

### ISSUE THREAD

**Issue by dlukauskis** [essex-lab/grand#4]
Hi, 

I'm trying to use _grand_ to equilibrate a protein-ligand system, but ran into some issues with getting _grand_ to understand the ligand parameters. I've followed the scytalone example, but I didn't have the prepi files, so I used MOL2 instead. I get the XML file but when I try to define the system, I get the following error:
```
ValueError: No template found for residue 299 (UNK).  The set of atoms matches UNK-0, but the bonds are different.
```
[I'm attaching all the files and the NB with the code.](https://github.com/essex-lab/grand/files/7570291/tmp.zip)

**Comment by olliemelling** [comment]
Hi,

This problem seems to be arising from how you are setting up your system. It looks like when you re-write the CONECT lines when adding the ligand back into the structure after solvation that something is going wrong and hence the resulting xml file is incorrect and OpenMM throws an error.

Is there a reason as to why you are removing the ligand from the protein structure before solvating? This isn't a typical approach given waters may be placed where the ligand should be, resulting in steric clashes when the ligand is added back into the structure. This has happened in your `protein_solvated.pdb` file where there is a water overlapping with the ligand.

I followed the steps below and it seemed to work fine:

- `antechamber` to generate the mol2 file from the PDB
- `parmchk2` to generate the frcmod file from the mol2 
- `tleap` to generate the amber topology and co-ordinate files
- `openmoltools.utils.create_ffxml_file()` to generate the XML file
- OpenMM to solvate the `protein_ligand.pdb` file, with the above XML file included when creating the `ForceField` object

Can you try this and see if it works for you? If there are still problems then please let me know.

Many thanks,
Ollie

**Comment by dlukauskis** [comment]
Yeah, that fixed this problem. I do have a couple of ligands that raise the same error, but I think this is an issue with openmoltools and not _grand_.
