### ISSUE TITLE
No registered platform called "CUDA"

### ISSUE THREAD

**Issue by freewbs** [essex-lab/grand#7]
Hello, I encountered the following error after installation while running the example. 
It looks like related to CUDA, any chance you have encoutered wittth this before?
```python
Traceback (most recent call last):
  File "equil-uvt1.py", line 60, in <module>
    platform = Platform.getPlatformByName('CUDA')
  File "/opt/conda/envs/grand/lib/python3.7/site-packages/simtk/openmm/openmm.py", line 17865, in getPlatformByName
    return _openmm.Platform_getPlatformByName(name)
Exception: There is no registered Platform called "CUDA"
```

**Comment by olliemelling** [comment]
Hi,

This is an issue with OpenMM not being able to find your CUDA installation. Do you know what version of CUDA you have installed? If you follow the instructions in https://github.com/essex-lab/grand/issues/6 you can change the `conda install -c omnia openmm=7.4.2` line for an OpenMM version that is compiled with the same version of CUDA that you have, as per https://anaconda.org/omnia/openmm.

E.g. if you have CUDA 10.1 installed then run `conda install -c omnia/label/cuda101 openmm=7.4.2`

You can check your installation by running `python -m simtk.testInstallation`.

An alternative is to try running with the OpenCL platform instead of CUDA. 

Let me know if this works - if you still have problems I would recommend looking at the OpenMM documentation as this is an issue with OpenMM and not grand.

Thanks,

Ollie
